// npm run style-gallery [-- <id> …] [--gallery <dir>]
// Builds styles/gallery (one worked example scene per style preset, film/scenes/<id>.js) into a playable film:
// copies in film-kit.js and the starter lib.js, bundles every preset's fonts, writes film.html, then renders
// each scene's "Cover" beat to styles/previews/<id>.jpg (960×540) for the style picker. Needs network for fonts.
// --gallery <dir> works on another folder shaped like styles/gallery (its previews go in <dir>/previews), so
// examples can be drafted without touching the shipped ones.
import { existsSync } from "node:fs";
import { copyFile, readdir, readFile, writeFile } from "node:fs/promises";
import { mkdir } from "node:fs/promises";
import { join, resolve } from "node:path";
import { bundleFonts, styleFonts } from "../server/fonts.ts";
import { openFilm, renderLayers } from "../server/chrome.ts";
import { ROOT, die, done, parseArgs } from "./_lib.ts";

const args = parseArgs();
const styles = join(ROOT, "styles");
const gallery = typeof args.flags.gallery === "string" ? resolve(process.env.INIT_CWD || process.cwd(), args.flags.gallery) : join(styles, "gallery");
const film = join(gallery, "film"), previews = args.flags.gallery ? join(gallery, "previews") : join(styles, "previews");
await mkdir(previews, { recursive: true });
const ids = (await readdir(join(film, "scenes"))).filter((f) => f.endsWith(".js")).map((f) => f.slice(0, -3)).sort();
const only = args._.length ? args._ : ids;
for (const id of only) if (!ids.includes(id)) die(`No example for "${id}" in styles/gallery/film/scenes/.`);

await copyFile(join(ROOT, "film-kit", "film-kit.js"), join(film, "film-kit.js"));
const lib = await readFile(join(ROOT, "templates", "films", "starter", "film", "lib.js"), "utf8");
await writeFile(join(film, "lib.js"), lib.replaceAll("{{TITLE}}", "Style gallery").replace("background: '#f7f7f5'", "background: '#000'"));
await writeFile(join(film, "styles.css"), `/* Style gallery. Generated by npm run style-gallery: each example scene styles itself under .g-<id>. */
.fk-stage { color: #111; background: #000; -webkit-font-smoothing: antialiased; }
.abs { position: absolute; left: 0; top: 0; }
`);
// Every preset's fonts, one entry per family (the widest axes win, since presets share families at different
// weights). Everything is bundled by text: the characters of all the examples plus Latin-1, so CJK and symbol
// glyphs come along and a shared family isn't cut down to one preset's copy.
const specs = new Map<string, string>();
for (const id of ids) {
  const md = join(styles, `${id}.md`);
  if (!existsSync(md)) continue;
  for (const f of styleFonts(await readFile(md, "utf8")).families) {
    const name = f.split(":")[0], had = specs.get(name);
    if (!had || (f.includes("..") && !had.includes("..")) || (f.includes("..") === had.includes("..") && f.length > had.length)) specs.set(name, f);
  }
}
let chars = "";
for (let c = 0x20; c <= 0xff; c++) if (c < 0x7f || c > 0xa0) chars += String.fromCharCode(c);
for (const id of ids) chars += (await readFile(join(film, "scenes", `${id}.js`), "utf8")).replace(/\s/g, "");
// one request per family keeps a bad name from failing the rest
for (const f of specs.values()) await bundleFonts(film, [f], chars).catch((e) => console.error(`  font ${f}: ${e.message}`));
await writeFile(join(gallery, "film.html"), `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Style gallery</title>
<link rel="stylesheet" href="film/styles.css">
</head>
<body>
<script src="film/film-kit.js"></script>
<script src="film/lib.js"></script>
${ids.map((id) => `<script src="film/scenes/${id}.js"></script>`).join("\n")}
<script src="film/edit.js"></script>
</body>
</html>
`);

const fp = await openFilm(join(gallery, "film.html"), 0.5);
let failed = 0;
try {
  for (const id of only) {
    const s = fp.manifest.scenes.find((x) => x.id === id);
    if (!s || s.error) { console.error(`${id}: ${s?.error?.split("\n")[0] || "not in the film"}`); failed++; continue; }
    const cover = s.beats?.find((b) => b.label === "Cover")?.t ?? (s.start + s.end) / 2;
    await renderLayers(fp.page, [{ scene: id, t: cover, opacity: 1 }]);
    await writeFile(join(previews, `${id}.jpg`), await fp.page.screenshot({ type: "jpeg", quality: 84 }));
    console.log(`${join(previews, `${id}.jpg`)}  (t ${cover})`);
  }
} finally { await fp.close(); }
console.log(`\nPlay it: open ${join(gallery, "film.html")} in a browser.`);
await done(failed ? 1 : 0);
